### ISSUE TITLE
incorrect decomp of BREAK from WITH operator

### ISSUE THREAD

**Issue by themabus** [UnderminersTeam/UndertaleModTool#1053]
### Describe the bug

```
tree = instance_create(x,y,oTree);
tree.leaves = true;
dog = instance_create(x,y,oDog);
dog.tail = true;

none = true;

with (oTree)
    if (other.speed <= 0) {
        if other.speed == -1 break;//broken
//        if other.speed == -2 continue;//werk
        leaves = !leaves;
        other.none = !other.none;
        show_debug_message('tree');
    }
with (oDog)
    if (other.speed <= 0) {
        tail = !tail;
        other.none = !other.none;
        show_debug_message('dog');
    }
```
when decompiled, provided code produces incorrect output possibly in all version (I checked 0.3.0, 0.3.5.8, 0.4.0.4, 674c5d8)

```
tree = instance_create(x, y, oTree)
tree.leaves = 1
dog = instance_create(x, y, oDog)
dog.tail = 1
none = 1
with (oTree)
{
    if (other.speed <= 0)
    {
        if (other.speed == -1)
        {
        }
        else
        {
            leaves = (!leaves)
            other.none = (!other.none)
            show_debug_message("tree")
        }
    }
    with (oDog)
    {
        if (other.speed <= 0)
        {
            tail = (!tail)
            other.none = (!other.none)
            show_debug_message("dog")
        }
    }
}
```

attached example is such that incorrect code won't run but in many cases produced code, even though incorrect, will be valid and will execute

### Reproducing steps

decompile attached thing
[bug_with.zip](https://github.com/krzys-h/UndertaleModTool/files/9180298/bug_with.zip)

### Setup Details

674c5d8
Win 10 x64

**Comment by themabus** [comment]
when encountered inside SWITCH statement, like so:
```
switch(x){
    case 0:
        with(oDog){
            if(tail < 1) {
                other.none = 777;
                break;
            }
        }
    break;
}
```
decompiler rises following exception:
```
/* EXCEPTION!
   System.Exception: Assertion failed! temp != switchEnd
   at UndertaleModLib.Util.DebugUtil.Assert(Boolean expr, String msg) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Util\DebugUtil.cs:line 16
   at UndertaleModLib.Decompiler.Decompiler.HLDecompileBlocks(DecompileContext context, Block& block, Dictionary`2 blocks, Dictionary`2 loops, Dictionary`2 reverseDominators, List`1 alreadyVisited, Block currentLoop, Block stopAt, Block breakTo, Boolean decompileTheLoop, UInt32 depth) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 3542
   at UndertaleModLib.Decompiler.Decompiler.HLDecompile(DecompileContext context, Dictionary`2 blocks, Block entryPoint, Block rootExitPoint) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 3660
   at UndertaleModLib.Decompiler.Decompiler.Decompile(UndertaleCode code, GlobalDecompileContext globalContext) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 3772
   at UndertaleModTool.UndertaleCodeEditor.<>c__DisplayClass31_1.<DecompileCode>b__1() in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModTool\Editors\UndertaleCodeEditor.xaml.cs:line 456
*/
```
[bug_with3.zip](https://github.com/krzys-h/UndertaleModTool/files/9289633/bug_with3.zip)
