### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added

### ISSUE THREAD

**Issue by Plackys** [UnderminersTeam/UndertaleModTool#1398]
### Describe the bug

When editing code inside undertale i got this error
when im editing a code it got an error so i restore the original code back and then this happen

/* EXCEPTION!
   System.ArgumentException: An item with the same key has already been added. Key: 293
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at UndertaleModLib.Decompiler.Decompiler.Decompile(UndertaleCode code, GlobalDecompileContext globalContext, Action`1 msgDelegate) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 3805
   at UndertaleModTool.UndertaleCodeEditor.<>c__DisplayClass43_1.<DecompileCode>b__1() in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModTool\Editors\UndertaleCodeEditor.xaml.cs:line 653
*/

### Reproducing steps

1.go to the code to edit
2.change the code a little bit
3.change the code to the original again
4.then that happen

### Setup Details

UTMT 0.5.1.0
windows 10
Undertale

**Comment by hankster112** [comment]
Same issue as well when editing another GM game.

UTMT 0.5.1.0
Devuan Linux (running through Wine)

**Comment by Jacky720** [comment]
Please update to the latest Bleeding Edge release.

**Comment by hankster112** [comment]
> Please update to the latest Bleeding Edge release.

I did, same issue

**Comment by Jacky720** [comment]
Strange. Do you know the approximate release date of your game, and can you send the decompiled code you were editing?

**Comment by Plackys** [comment]
> Please update to the latest Bleeding Edge release.
i already update to the latest bleeding edge build

**Comment by Miepee** [comment]
@Plackys what game was this?

**Comment by Miepee** [comment]
Simce we have no info to reproduce this, I'm going to close the issue.
Feel free to reopen it if you can provide more info
