### ISSUE TITLE
(NSFW) Secret Care cafe - the estimated object pool size differs from the actual size

### ISSUE THREAD

**Issue by dragoonmaster999** [UnderminersTeam/UndertaleModTool#1646]
### Describe the bug

When I open a game with external textures (.yytex files) the warning on the title appeared.

### Reproducing steps

>Open data.win
>Warning "Warning - the estimated object pool size differs from the actual size"
>Open anyways
>Views sprites
>No visible problems
>Closes

### Setup Details

>Undertale Mod Tool v. 0.5.1.0
>Windows 11 OS
>Games with gamemaker js and external textures.

**Comment by Miepee** [comment]
> Games with gamemaker js and external textures.

Which games? can you link them?

**Comment by suphamster** [comment]
Same issue for me, game link (press "No thanks, just take me to the downloads" there) https://rarealexturan.itch.io/secretcarecafe/purchase (warning: NSFW game!). 
Since CLI version gives more info about error here is log:
```
UndertaleModCli info data.win
Trying to load file: 'G:\Games\Secret Care Cafe 0.8.26 Patreon\data.win'
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException: Warning - the estimated object pool size differs from the actual size.
Please report this on UndertaleModTool GitHub.
   at UndertaleModLib.UndertaleReader.SubmitWarning(String warning) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\UndertaleIO.cs:line 199
   at UndertaleModLib.UndertaleReader.ProcessCountExc(UInt32 poolSize) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\UndertaleIO.cs:line 346
   at UndertaleModLib.UndertaleReader.ReadUndertaleData() in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\UndertaleIO.cs:line 282
   at UndertaleModLib.UndertaleIO.Read(Stream stream, WarningHandlerDelegate warningHandler, MessageHandlerDelegate messageHandler, Boolean onlyGeneralInfo) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\UndertaleIO.cs:line 912
   at UndertaleModCli.Program.ReadDataFile(FileInfo datafile, WarningHandlerDelegate warningHandler, MessageHandlerDelegate messageHandler) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModCli\Program.cs:line 792
   at UndertaleModCli.Program..ctor(FileInfo datafile, Boolean verbose, DirectoryInfo output) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModCli\Program.cs:line 209
   at UndertaleModCli.Program.Info(InfoOptions options) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModCli\Program.cs:line 314
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by VladiStep** [comment]
> Secret Care Cafe
Oh, I remember it.
Some time ago you also couldn't open it, but because of its size, and I fixed that.
And now it strikes again :D

**Comment by VladiStep** [comment]
Wait, the CLI version doesn't even allow you to load the file if there's a warning?

**Comment by suphamster** [comment]
> Wait, the CLI version doesn't even allow you to load the file if there's a warning?

Yes, in GUI at least it loads with warning, but CLI version doesn't allow to do anything after those error.

**Comment by VladiStep** [comment]
Just made [an issue](https://github.com/krzys-h/UndertaleModTool/issues/1652) about that.

**Comment by VladiStep** [comment]
Okay, it seems that the object counting stage doesn't see the external textures.

**Comment by suphamster** [comment]
> Okay, it seems that the object counting stage doesn't see the external textures.

Thx, ur recent commit ccb3212 fixed crash on CLI but what about external textures fix? In GUI version I'm able to export/view external textures but CLI version just does nothing with "UndertaleModCli dump -t data.win" command.
