### ISSUE TITLE
Null Reference Exception When Adding New Texture Page Item or Embedded Texture

### ISSUE THREAD

**Issue by Garethp** [UnderminersTeam/UndertaleModTool#1898]
### Describe the bug

When attempting to add a new Texture Page Item or Embedded Texture to the `data.win` file of Fields of Mistria, you receive an NRE. Specifically, adding a new Texture Page Item results in the following error

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at UndertaleModTool.UndertaleTexturePageItemEditor.UpdateImages(UndertaleTexturePageItem item) in D:\SteamLibrary\steamapps\common\RimWorld\Mods\UndertaleModTool\UndertaleModTool\Editors\UndertaleTexturePageItemEditor.xaml.cs:line 43
   at UndertaleModTool.UndertaleTexturePageItemEditor.SwitchDataContext(Object sender, DependencyPropertyChangedEventArgs e) in D:\SteamLibrary\steamapps\common\RimWorld\Mods\UndertaleModTool\UndertaleModTool\Editors\UndertaleTexturePageItemEditor.xaml.cs:line 56
   at System.Windows.FrameworkElement.OnDataContextChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at UndertaleModTool.DataUserControl.OnPropertyChanged(DependencyPropertyChangedEventArgs e) in D:\SteamLibrary\steamapps\common\RimWorld\Mods\UndertaleModTool\UndertaleModTool\Controls\DataUserControl.cs:line 17
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.TreeWalkHelper.InvalidateTreeDependentProperty(TreeChangeInfo info, DependencyObject d, FrameworkObject& fo, DependencyProperty dp, FrameworkPropertyMetadata fMetadata, Style selfStyle, Style selfThemeStyle, ChildRecord& childRecord, Boolean isChildRecordValid, Boolean hasStyleChanged, Boolean isSelfInheritanceParent, Boolean wasSelfInheritanceParent)
...
``` 

While adding a new Embedded Texture gives the following

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at UndertaleModTool.MainWindow.GetBitmapSourceForImage(GMImage image) in D:\SteamLibrary\steamapps\common\RimWorld\Mods\UndertaleModTool\UndertaleModTool\MainWindow.xaml.cs:line 293
   at UndertaleModTool.UndertaleEmbeddedTextureEditor.UpdateImage(UndertaleEmbeddedTexture texture) in D:\SteamLibrary\steamapps\common\RimWorld\Mods\UndertaleModTool\UndertaleModTool\Editors\UndertaleEmbeddedTextureEditor.xaml.cs:line 73
   at UndertaleModTool.UndertaleEmbeddedTextureEditor.SwitchDataContext(Object sender, DependencyPropertyChangedEventArgs e) in D:\SteamLibrary\steamapps\common\RimWorld\Mods\UndertaleModTool\UndertaleModTool\Editors\UndertaleEmbeddedTextureEditor.xaml.cs:line 84
   at System.Windows.FrameworkElement.OnDataContextChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at UndertaleModTool.DataUserControl.OnPropertyChanged(DependencyPropertyChangedEventArgs e) in D:\SteamLibrary\steamapps\common\RimWorld\Mods\UndertaleModTool\UndertaleModTool\Controls\DataUserControl.cs:line 17
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
...
```

Running the latest Undertale Mod Tool in through a debugger shows that when creating either of those items, their respective `SwitchDataContext` method is being called to update the view model with the newly created items. Both of those view controllers have null checks on the item itself ([exmaple](https://github.com/UnderminersTeam/UndertaleModTool/blob/dc1e209759472845681f66b1dafffcd1a1d46867/UndertaleModTool/Editors/UndertaleTexturePageItemEditor.xaml.cs#L52)) however the newly created item isn't null, either the TextureData or the Image of it is null. I feel like this is to be expected, since they're newly created and not yet assigned a source bitmap to be referencing, but I'm unfamiliar with Undertale Mod Tool.

### Reproducing steps

1. Open the data.win file from Fields of Mistria
2. Right-click "Texture Page Items" in the right menu
3. Click "Add" and see an error message

or

1. Open the data.win file from Fields of Mistria
2. Right-click "Embedded Textures" in the right menu
3. Click "Add" and see an error message

### Setup Details

1. Undertale Mod Tool Verison: `0.6.1.0` and `dc1e209759472845681f66b1dafffcd1a1d46867`
2. Operating System: Windows 10
3. [Fields of Mistria](https://store.steampowered.com/app/2142790/Fields_of_Mistria/)

**Comment by colinator27** [comment]
Looks like I forgot to check these cases, good catch! I'm assuming this is specific to the development version of the tool, as release 0.6.1.0 does not have the recent texture changes (which added these two functions).

**Comment by Garethp** [comment]
I've opened an MR. This also occurs in version 0.6.1.0. I think they may have slipped in under either `74d3ccf9`, when you rewrote texture handling to update to .NET 8

**Comment by colinator27** [comment]
Those changes are not merged into the actual release of 0.6.1.0, so this only happens on the development version (I just tested). Thanks for the PR!

**Comment by Garethp** [comment]
Oh cheers, I must have gotten it very mixed up. No worries, and thanks for the tool!

**Comment by Natedogwoooof** [comment]
same was gonna report it till i found this issue lol
