### ISSUE TITLE
Decompilation error: Tried to pushaf on something that is not a var

### ISSUE THREAD

**Issue by craftersshaft** [UnderminersTeam/UndertaleModTool#1922]
### Describe the bug

The decompiler throws an exception when decompiling code, and currently the game is on the latest GM compiler. Opening the game with the Underanalyzer build seems to work fine, but saving the code makes another error happen.

### Reproducing steps

![image](https://github.com/user-attachments/assets/c8bb88e6-1520-4da0-8589-50d12890d478)
1. Open data.win in UndertaleModTool
2. open Code > gml_Object_obj_char_Crack_Step_0

```EXCEPTION!
   System.InvalidOperationException: Tried to pushaf on something that is not a var
   at UndertaleModLib.Decompiler.Decompiler.DecompileFromBlock(DecompileContext context, Dictionary`2 blocks, Block block, List`1 tempvars, Stack`1 workQueue) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 647
   at UndertaleModLib.Decompiler.Decompiler.DecompileFromBlock(DecompileContext context, Dictionary`2 blocks, Block block) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 800
   at UndertaleModLib.Decompiler.Decompiler.Decompile(UndertaleCode code, GlobalDecompileContext globalContext, Action`1 msgDelegate) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 1465
   at UndertaleModTool.UndertaleCodeEditor.<>c__DisplayClass58_1.<DecompileCode>b__1() in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModTool\Editors\UndertaleCodeEditor.xaml.cs:line 700
```

### Setup Details

UndertaleModTool Bleeding Edge (git: https://github.com/UnderminersTeam/UndertaleModTool/commit/9f4f13a52495f82663dd125c0028519850faba83)
Windows 10
Supra Smash Bross Devolution https://reynlynxpsi.itch.io/supra-smash-bross

**Comment by colinator27** [comment]
Likely properly fixed with https://github.com/UnderminersTeam/UndertaleModTool/pull/2056.

**Comment by colinator27** [comment]
This should now be fixed on the latest bleeding edge release. I'll close this issue for now, but feel free to re-open it if it's still broken.
