### ISSUE TITLE
UML compiler doesn't support functions outside scripts

### ISSUE THREAD

**Issue by ChronoVortex** [UnderminersTeam/UndertaleModTool#1945]
### Describe the bug

Attempting to compile this GML code in an object's creation event
```
anon_func = function()
{
    show_debug_message("ANON FUNC");
};

anon_func();
```
Results in this error
```
;  EXCEPTION!
;   System.ArgumentException: An item with the same key has already been added. Key: 1
;   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
;   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
;   at UndertaleModLib.Decompiler.Disassembler.Disassemble(UndertaleCode code, IList`1 vars, UndertaleCodeLocals locals) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Disassembler.cs:line 58
;   at UndertaleModTool.UndertaleCodeEditor.DisassembleCode(UndertaleCode code, Boolean first) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModTool\Editors\UndertaleCodeEditor.xaml.cs:line 531
```

### Reproducing steps

Attempt to compile a non-script function.

### Setup Details

Reproduced on a test project compiled in the latest release of GMS2.
[data.zip](https://github.com/user-attachments/files/17275709/data.zip)

**Comment by colinator27** [comment]
This should now be fixed on the latest bleeding edge release. I'll close this issue for now, but feel free to re-open it if it's still broken.
