### ISSUE TITLE
No component

### ISSUE THREAD

**Issue by hhbjuuigytyg** [UnderminersTeam/UndertaleModTool#1987]
### Describe the bug

/* EXCEPTION!
   System.NotImplementedException: Missing ref type 6
   at UndertaleModLib.Decompiler.Decompiler.ExpressionAssetRef.DoTypePropagation(DecompileContext context, AssetIDType suggestedType) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Instructions\Decompiler.ExpressionAssetRef.cs:line 126
   at UndertaleModLib.Decompiler.Decompiler.DirectFunctionCall.DoTypePropagation(DecompileContext context, AssetIDType suggestedType) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Instructions\Decompiler.DirectFunctionCall.cs:line 177
   at UndertaleModLib.Decompiler.Decompiler.DoTypePropagation(DecompileContext context, Dictionary`2 blocks) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 1585
   at UndertaleModLib.Decompiler.Decompiler.Decompile(UndertaleCode code, GlobalDecompileContext globalContext, Action`1 msgDelegate) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 1466
   at UndertaleModTool.UndertaleCodeEditor.<>c__DisplayClass58_0.<DecompileCode>b__1() in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModTool\Editors\UndertaleCodeEditor.xaml.cs:line 700
*/

### Reproducing steps

File - gml_Object_obj_dialogue_battle_Step_1
![UndertaleModTool_V6RFWTfirK](https://github.com/user-attachments/assets/c3dc867f-2cb0-46d6-8dfe-42455f3ac954)

### Setup Details

Windows 10. game is Undertale Wildfire

**Comment by colinator27** [comment]
This is likely fixed in the `underanalyzer` branch/PR, if you want to try it out there. Latest build artifacts (downloads) can be found at https://github.com/UnderminersTeam/UndertaleModTool/actions/runs/12109954136?pr=1862.

**Comment by colinator27** [comment]
This should now be fixed on the latest bleeding edge release. I'll close this issue for now, but feel free to re-open it if it's still broken.
