### ISSUE TITLE
Recompiling ``alpha=(0.5+(color==global.color||color==c_white)*0.5);`` causes a decompiler error.

### ISSUE THREAD

**Issue by Grossley** [UnderminersTeam/UndertaleModTool#256]
Recompiling ``alpha=(0.5+(color==global.color||color==c_white)*0.5);`` causes this error:

```
EXCEPTION!
System.Exception: Malformed switch statement: bad condition var (color)
   at UndertaleModLib.Decompiler.Decompiler.HLDecompileBlocks(DecompileContext context, Block& block, Dictionary`2 blocks, Dictionary`2 loops, Dictionary`2 reverseDominators, List`1 alreadyVisited, Block currentLoop, Block stopAt, Block breakTo, Boolean decompileTheLoop) in C:\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 2338
   at UndertaleModLib.Decompiler.Decompiler.HLDecompile(DecompileContext context, Dictionary`2 blocks, Block entryPoint, Block rootExitPoint) in C:\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 2494
   at UndertaleModLib.Decompiler.Decompiler.Decompile(UndertaleCode code, DecompileContext context) in C:\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 2593
   at UndertaleModTool.UndertaleCodeEditor.<>c__DisplayClass11_0.<DecompileCode>b__0() in C:\UndertaleModTool\UndertaleModTool\Editors\UndertaleCodeEditor.xaml.cs:line 296
```

The new disassembly resulting from compilation is nearly identical to the original disassembly source (which had an identical error) so it is evident to me that it is not a compiler issue but rather a decompiler issue. 

Original disassembly:
```
.localvar 0 arguments
00000: push.d 0.5
00003: push.v self.color
00005: pushglb.v global.color
00007: cmp.v.v EQ
00008: bt 00015
00009: push.v self.color
00011: push.i 16777215
00013: cmp.i.v EQ
00014: b 00016
00015: push.e 1
00016: conv.b.i
00017: push.d 0.5
00020: mul.d.i
00021: add.d.d
00022: pop.v.d self.alpha
```
New disassembly:
```
.localvar 0 arguments
00000: push.d 0.5
00003: push.v self.color
00005: pushglb.v global.color
00007: cmp.v.v EQ
00008: bt 00015
00009: push.v self.color
00011: push.i 16777215
00013: cmp.i.v EQ
00014: b 00016
00015: push.e 1
00016: conv.b.i
00017: push.d 0.5
00020: mul.d.d
00021: add.d.d
00022: pop.v.d self.alpha
```

**Comment by colinator27** [comment]
So my guess is that the switch statement detector triggers even though this code is already part of an expression, it's not an if statement, and it uses short circuit operations. Not sure how to prevent it completely, though

**Comment by colinator27** [comment]
Some more similar test cases at https://github.com/krzys-h/UndertaleModTool/issues/276#issue-593622427 and https://github.com/krzys-h/UndertaleModTool/issues/276#issuecomment-608644225.
